name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Build Release
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/hupdater.exe
          generate_release_notes: true
          draft: false
          prerelease: false
